### ISSUE TITLE
Update Interval is too long (30min)

### ISSUE THREAD

**Issue by SiriusLightning21** [yanascz/bitcoin-widgets-android#1]
The refreshing interval for the widget is too long.  Is it possible to put a button on the widget that triggers the update or that the widget updated as soon as the display is switched on. I think the second one is the best solution. I hope you can help.

**Comment by yanascz** [comment]
Thanks, I’m aware of this issue. Once the app is finally approved (3rd try in progress), I’ll look into it. Updating the widgets after phone is unlocked seems ideal.

**Comment by yanascz** [comment]
@SiriusLightning21, could you please test the app from branch `issue-1-update-interval`? Now the widgets should be updated when screen is turned on.

**Comment by SiriusLightning21** [comment]
Yes this works for me. The only issue is that the app must run in backround to update after the screen goes on.

**Comment by yanascz** [comment]
The fix is in `master`, docs updated.
