### ISSUE TITLE
Moscow Time

### ISSUE THREAD

**Issue by daniele2010** [yanascz/bitcoin-widgets-android#3]
Hi, first congratulations for your work, finally a widget about timechain data!
Do you consider implementing a moscow time widget?

Thank you again

**Comment by yanascz** [comment]
Yep, it’s in my TODO list. However, I had to work on something else in the past several weeks. Hope to get to it soon. Please be patient. 🙏

**Comment by yanascz** [comment]
@daniele2010, it's available in https://github.com/yanascz/bitcoin-widgets-android/tree/moscow-time. You may build and deploy the branch via Android Studio and give it a try. 😉 Or wait for a Google Play update.

<img width="184" alt="image" src="https://user-images.githubusercontent.com/37251117/201489601-44c69631-b582-449a-a6a5-675720bb0761.png">

**Comment by daniele2010** [comment]
really appreciated! thank you again!!!

**Comment by yanascz** [comment]
Still waiting for app review, it's been in progress since Sunday. 🤷‍♂️

**Comment by daniele2010** [comment]
In the meantime, I've already built it! 😃

**Comment by yanascz** [comment]
Update available on Google Play. 🥳
