### ISSUE TITLE
Manual update

### ISSUE THREAD

**Issue by VojtechMyslivec** [yanascz/bitcoin-widgets-android#5]
Would it be possible to manually update the stats by clicking the widget on the screen?

Also, it would be perfect to include some graphics (like rotating circle or arrows) to have a visible feedback that the update successfully finished

Thanks for your work :+1:

**Comment by yanascz** [comment]
Tapping on widget content to refresh widgets shall be available in version 1.3 (currently in review). The tap sound is played (if enabled in OS settings) when the widget is tapped. Progress animation won't be available, though.

**Comment by yanascz** [comment]
Version 1.3 available in Google Play.
